version: '3.8'
services:
    movie_db:
        image: mysql:8.0
        ports:
            - 3307:3306
        environment:
            - MYSQL_DATABASE=movie_db
            - MYSQL_USER=ovie5th
            - MYSQL_PASSWORD=mauFJcuf5dhRMQrjj
            - MYSQL_ROOT_PASSWORD=password
        
    test-db:
        image: postgres:13
        ports:
            - 5435:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: nest


